apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "code-server-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-0fa6ef518d883e4c9" 
